// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlbhqxddnznlxbnyyvwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYmhxeGRkbnpubHhibnl5dndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODc4NDMsImV4cCI6MjA1Mjk2Mzg0M30.QqTJ37KUa7oXARi14j7fgQ0DJWYoNfb38mz_AEh2tHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);